cloud_provider: digital_ocean
cloud_providers:
  digital_ocean:
    region: New York 2
    image_id: 14.04 x64
    client_key: "#{ENV['DIGITAL_OCEAN_CLIENT_ID']}"
    api_key: "#{ENV['DIGITAL_OCEAN_API_KEY']}"
    key_dir: "#{(File.expand_path('~') rescue '/root') + '/.ssh/digitalocean-project-name' }"
    key_name: "#{`whoami`.chomp}"
    key_file: "#{Dir[key_dir + '/*' + key_name].first}"
    private_networking: false
  aws:
    access_key: "#{ENV['AWS_ACCESS_KEY_ID']}"
    secret_access_key: "#{ENV['AWS_SECRET_ACCESS_KEY']}"
environments:
  staging:
    cloud_providers:
      digital_ocean:
        image_type: 2GB
    unicorn_worker_count: 6
  production:
    cloud_providers:
      digital_ocean:
        image_type: 2GB
    unicorn_worker_count: 6

backup_bucket: "project-name-backups"