source 'https://rubygems.org'

ruby '2.0.0'

# Rails Defaults
gem 'rails', '4.0.0'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

# Boilerplate Defaults
gem 'airbrake'
gem 'rails_admin'
gem 'devise'
gem 'omniauth'
gem 'cancan'
gem 'paperclip'
gem 'aws-sdk'
gem 'unicorn'
gem 'asset_sync'

group :production, :staging do
  gem 'rails_12factor'
end

group :development do
  gem 'debugger'
  gem 'letter_opener'
end

group :test do
  gem 'debugger'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'poltergeist'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
end

# Additonal