# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin('vagrant-omnibus')
Vagrant.require_plugin('vagrant-librarian-chef')

Vagrant.configure("2") do |config|
  config.omnibus.chef_version = :latest

  config.vm.box = "precise64-twinenginelabs"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/194837816/precise64-twinenginelabs.box"
  config.vm.network :forwarded_port, guest: 3000, host: 3000  
  config.vm.synced_folder ".", "/home/vagrant/app"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks"]

    chef.add_recipe "apt"
    chef.add_recipe "build-essential"
    chef.add_recipe "git"
    chef.add_recipe "ruby_build"
    chef.add_recipe "rbenv::system"
    chef.add_recipe "postgresql::server"
    chef.add_recipe "nodejs"
    chef.add_recipe "imagemagick"

    chef.json.merge!({
      rbenv: {
        rubies: ['2.0.0-p247'],
        global: '2.0.0-p247',
        gems: {
          '2.0.0-p247' => [
            name: 'bundler'
          ]
        }
      },
      postgresql: {
        password: {
          postgres: 'postgres'
        },
        config: {
          ssl: false,
          listen_addresses: '*'
        },
        pg_hba: [
          { type: 'local', db: 'all', user: 'all', addr: nil, method: 'trust' },
          { type: 'host',  db: 'all', user: 'all', addr: '127.0.0.1/32', method: 'trust' },
          { type: 'host',  db: 'all', user: 'all', addr: '::1/128', method: 'trust' }
        ]
      }
    })
  end

  config.vm.provision :shell, :inline => <<-EOS
    cd app
    bundle --quiet
    bundle exec rake db:create
    bundle exec rake db:migrate
  EOS
end